      PROGRAM MAIN
      INTEGER :: STATUS,UNIT,FPIXELS(3),LPIXELS(3),M,N,NPIXELS,
     &  BUFFERSIZE,I
      DOUBLE PRECISION, ALLOCATABLE :: ARRAY(:)
      CHARACTER(LEN=256) :: FILENAME,ARG,AVGFILE,DATESTR
      STATUS=0
      CALL GETARG(1,FILENAME)
      WRITE(*,'(2A)') ' Input: ',TRIM(FILENAME)
      CALL GETARG(2,ARG)
      READ(ARG,*) FPIXELS(1),FPIXELS(2),FPIXELS(3)
      CALL GETARG(3,ARG)
      READ(ARG,*) LPIXELS(1),LPIXELS(2),LPIXELS(3)
      CALL GETARG(4,ARG)
      READ(ARG,*) BUFFERSIZE
      CALL GETARG(5,AVGFILE)
      M=LPIXELS(1)-FPIXELS(1)+1
      N=LPIXELS(2)-FPIXELS(2)+1
      NPIXELS=M*N
      ALLOCATE(ARRAY(NPIXELS))
      I=TIME()
      CALL CTIME(I,DATESTR)
      PRINT *,TRIM(DATESTR),' start averaging.'
      CALL AVERAGE(TRIM(FILENAME),FPIXELS,LPIXELS,ARRAY,BUFFERSIZE)
      I=TIME()
      CALL CTIME(I,DATESTR)
      PRINT *,TRIM(DATESTR),' finished averaging.'
      CALL WRITEIMAGE(TRIM(AVGFILE),(/1,1,1/),(/M,N,1/),ARRAY)
      WRITE(*,'(2A)') ' Output: ',TRIM(AVGFILE)
      DEALLOCATE(ARRAY)
      STOP
      END PROGRAM
