      PROGRAM MAIN
      INTEGER :: FPIXELS(3),LPIXELS(3),NAXES(3),K,NARGS
      DOUBLE PRECISION, ALLOCATABLE :: ARRAY(:,:)
      CHARACTER(LEN=256) :: FILENAME,ARG,AVGFILE,DATESTR
      INTERFACE
      INCLUDE 'ispeckle.f'
      END INTERFACE
      NARGS=COMMAND_ARGUMENT_COUNT()
      CALL IMAGESIZE(FILENAME,NAXES)
      CALL GET_COMMAND_ARG(1,FILENAME)
      CALL GETARG(2,ARG)
      READ(ARG,*) FPIXELS(1),FPIXELS(2),FPIXELS(3)
      CALL GETARG(3,ARG)
      READ(ARG,*) LPIXELS(1),LPIXELS(2),LPIXELS(3)
      CALL GETARG(4,AVGFILE)
      WRITE(*,'(2A)') ' Input: ',TRIM(FILENAME)
      ALLOCATE(ARRAY(NPIXELS))
      CALL AVERAGE(TRIM(FILENAME),FPIXELS,LPIXELS,ARRAY)
      CALL WRITEIMAGE(TRIM(AVGFILE),(/1,1,1/),(/M,N,1/),ARRAY)
      WRITE(*,'(2A)') ' Output: ',TRIM(AVGFILE)
      DEALLOCATE(ARRAY)
      STOP
      END PROGRAM
