      PROGRAM MAIN
      IMPLICIT NONE
      INTEGER :: FPIXELS(3),LPIXELS(3)
      CHARACTER(LEN=256) :: ARG,TARGFILE,FLATFILE,DARKFILE,CRCTFILE
      CALL GETARG(1,TARGFILE)
      CALL GETARG(2,ARG)
      READ(ARG,*) FPIXELS(1),FPIXELS(2),FPIXELS(3)
      CALL GETARG(3,ARG)
      READ(ARG,*) LPIXELS(1),LPIXELS(2),LPIXELS(3)
      CALL GETARG(4,FLATFILE)
      CALL GETARG(5,DARKFILE)
      CALL GETARG(6,CRCTFILE)
      CALL FLATFIELDCORRECT(TARGFILE,FPIXELS,LPIXELS,FLATFILE,DARKFILE,
     &  CRCTFILE)
      STOP
      END PROGRAM MAIN
