      PROGRAM IMAGESC
      IMPLICIT NONE
      REAL,PARAMETER :: GL(2)=(/0.0, 1.0/),GR(2)=(/0.0, 1.0/),
     &  GG(2)=(/0.0, 1.0/),GB(2)=(/0.0, 1.0/)
      INTEGER :: STATUS,NAXES(3)
      REAL :: TR(6)
      DOUBLE PRECISION,ALLOCATABLE :: DIMG(:,:)
      CHARACTER(LEN=256) :: IMGFILE
C
      INTERFACE
      SUBROUTINE READIMAGE(FILENAME,FPIXELS,LPIXELS,DIMG)
      INTEGER, INTENT(IN) :: FPIXELS(3),LPIXELS(3)
      DOUBLE PRECISION, INTENT(OUT) :: DIMG(*)
      CHARACTER(LEN=*), INTENT(IN) :: FILENAME
      END SUBROUTINE READIMAGE
      SUBROUTINE IMAGESIZE(FILENAME,NAXES)
      INTEGER, INTENT(OUT) :: NAXES(3)
      CHARACTER(LEN=*) :: FILENAME
      END SUBROUTINE IMAGESIZE
      FUNCTION PGOPEN(DEVICE)
      CHARACTER(LEN=*) :: DEVICE
      INTEGER :: PGOPEN
      END FUNCTION PGOPEN
      SUBROUTINE PGENV(XMIN,XMAX,YMIN,YMAX,JUST,AXIS)
      REAL :: XMIN,XMAX,YMIN,YMAX
      INTEGER :: JUST,AXIS
      END SUBROUTINE PGENV
      SUBROUTINE PGLAB(XLBL,YLBL,TOPLBL)
      CHARACTER(LEN=*) :: XLBL,YLBL,TOPLBL
      END SUBROUTINE PGLAB
      SUBROUTINE PGCLOS
      END SUBROUTINE
      SUBROUTINE PGIMAG(A,NI,NJ,I1,I2,J1,J2,A1,A2,TR)
      INTEGER :: NI,NJ,I1,I2,J1,J2
      REAL :: A(NI,NJ),A1,A2,TR(6)
      END SUBROUTINE PGIMAG
      SUBROUTINE PGSVP(XLEFT,XRIGHT,YBOT,YTOP)
      REAL :: XLEFT,XRIGHT,YBOT,YTOP
      END SUBROUTINE PGSVP
      SUBROUTINE PGPAGE
      END SUBROUTINE PGPAGE
      SUBROUTINE PGCTAB(L,R,G,B,NC,CONTRA,BRIGHT)
      INTEGER :: NC
      REAL :: L(NC),R(NC),G(NC),B(NC),CONTRA,BRIGHT
      END SUBROUTINE PGCTAB
      SUBROUTINE PGWNAD(X1,X2,Y1,Y2)
      REAL :: X1, X2, Y1, Y2
      END SUBROUTINE PGWNAD
      SUBROUTINE PGBOX(XOPT,XTICK,NXSUB,YOPT,YTICK,NYSUB)
      CHARACTER(LEN=*) :: XOPT, YOPT
      REAL :: XTICK, YTICK
      INTEGER :: NXSUB, NYSUB
      END SUBROUTINE PGBOX
      SUBROUTINE PGMTXT(SIDE,DISP,COORD,FJUST,TEXT)
      CHARACTER(LEN=*) :: SIDE, TEXT
      REAL :: DISP, COORD, FJUST
      END SUBROUTINE PGMTXT
      SUBROUTINE PGSCH(SZ)
      REAL :: SZ
      END SUBROUTINE PGSCH
      END INTERFACE
C
      STATUS=0
      CALL GET_COMMAND_ARGUMENT(1,IMGFILE)
      CALL IMAGESIZE(IMGFILE,NAXES)
      ALLOCATE(DIMG(NAXES(1),NAXES(2)),STAT=STATUS)
      IF(STATUS.NE.0)THEN
        WRITE(*,*)'error: out of memory.'
        STOP
      END IF
      CALL READIMAGE(IMGFILE,(/1,1,1/),(/NAXES(1),NAXES(2),1/),DIMG)
      IF(PGOPEN('?') .LT. 1)THEN
        STOP
      END IF
      TR=(/0.,1.,0.,0.,0.,1./)
      CALL PGPAGE
      CALL PGSVP(0.,1.,0.,1.)
      CALL PGWNAD(0.,1.0+REAL(NAXES(1)),0.,1.0+REAL(NAXES(2)))
      CALL PGCTAB(GL,GR,GG,GB,2,1.0,0.5)
      CALL PGIMAG(REAL(DIMG),NAXES(1),NAXES(2),1,NAXES(1),1,NAXES(2),
     &  REAL(MINVAL(DIMG)),REAL(MAXVAL(DIMG)),TR)
      CALL PGMTXT('t',1.0,0.0,0.0,'Estimate')
      CALL PGSCH(0.6)
      CALL PGBOX('bcntsi',0.0,0,'bcntsiv',0.0,0)
      CALL PGMTXT('b',3.0,1.0,1.0,'pixel number')
      CALL PGWEDG('BI',4.0,5.0,REAL(MINVAL(DIMG)),
     &  REAL(MAXVAL(DIMG)),'pixel value')
      CALL PGSCH(1.0)
      CALL PGCLOS
      DEALLOCATE(DIMG)
      STOP
      END PROGRAM IMAGESC
