      PROGRAM POISSRNDTEST
      IMPLICIT NONE
      INTEGER, PARAMETER :: KMAX = 10, L=4
      INTEGER :: K,RND(L,L)
      DOUBLE PRECISION :: DLAMBDA(L,L)
      INTERFACE
      SUBROUTINE INIT_RANDOM_SEED()
      END SUBROUTINE INIT_RANDOM_SEED
      FUNCTION POISSRND(DLAMBDA)
      INTEGER :: POISSRND
      DOUBLE PRECISION,INTENT(IN) :: DLAMBDA
      END FUNCTION POISSRND
      SUBROUTINE POISSRNDM(NX,NY,DLAMBDA,RND)
      INTEGER,INTENT(IN) :: NX,NY
      DOUBLE PRECISION,INTENT(IN) :: DLAMBDA(NX,NY)
      INTEGER,INTENT(OUT) :: RND(NX,NY)
      END SUBROUTINE POISSRNDM
      END INTERFACE
      DO K=1,L
        READ(*,*)DLAMBDA(:,K)
      END DO
      CALL INIT_RANDOM_SEED()
      DO K=1,KMAX
        CALL POISSRNDM(L,L,DLAMBDA,RND)
        WRITE(*,*) RND
      END DO
      STOP
      END PROGRAM POISSRNDTEST