      PROGRAM POISSRNDTEST
      IMPLICIT NONE
      INTEGER, PARAMETER :: KMAX = 10, L=4
      INTEGER :: K,RND(L)
      DOUBLE PRECISION :: DLAMBDA(L)
      INTERFACE
      SUBROUTINE INIT_RANDOM_SEED()
      END SUBROUTINE INIT_RANDOM_SEED
      FUNCTION POISSRND(DLAMBDA)
      INTEGER :: POISSRND
      DOUBLE PRECISION,INTENT(IN) :: DLAMBDA
      END FUNCTION POISSRND
      SUBROUTINE POISSRNDM(NX,NY,DLAMBDA,RND)
      INTEGER,INTENT(IN) :: NX,NY
      DOUBLE PRECISION,INTENT(IN) :: DLAMBDA(NX,NY)
      INTEGER,INTENT(OUT) :: RND(NX,NY)
      END SUBROUTINE POISSRNDM
      END INTERFACE
      READ(*,*)DLAMBDA
      CALL INIT_RANDOM_SEED()
      DO K=1,KMAX
        CALL POISSRNDM(L,1,DLAMBDA,RND)
        WRITE(*,*) RND
      END DO
      STOP
      END PROGRAM POISSRNDTEST