      PROGRAM POISSRNDTEST
      IMPLICIT NONE
      INTEGER, PARAMETER :: KMAX = 10
      INTEGER :: K
      DOUBLE PRECISION :: DLAMBDA
      INTERFACE
      SUBROUTINE INIT_RANDOM_SEED()
      END SUBROUTINE INIT_RANDOM_SEED
      FUNCTION POISSRND(DLAMBDA)
      INTEGER :: POISSRND
      DOUBLE PRECISION,INTENT(IN) :: DLAMBDA
      END FUNCTION POISSRND
      END INTERFACE
      READ(*,*)DLAMBDA
      CALL INIT_RANDOM_SEED()
      DO K=1,KMAX
        WRITE(*,*) POISSRND(DLAMBDA)
      END DO
      STOP
      END PROGRAM POISSRNDTEST