      PROGRAM SNR
      IMPLICIT NONE
      CHARACTER(LEN=256) :: IMGFILE,FLAGFILE,
      INTERFACE
      SUBROUTINE ESTSNR(IMGFILE,FLAGFILE,FITN,DSNR,PREFIX)
      INTEGER, INTENT(IN) :: FITN
      DOUBLE PRECISION, INTENT(OUT) :: DSNR
      CHARACTER(LEN=*), INTENT(IN) :: IMGFILE,FLAGFILE,PREFIX
      END SUBROUTINE ESTSNR
      END INTERFACE
      STOP
      END PROGRAM SNR