      PROGRAM MAIN
      INTEGER :: STATUS,UNIT,FPIXELS(3),LPIXELS(3),NAXES(3),NPIXELS
      CHARACTER :: FILENAME*80,ARG*255
      DOUBLE PRECISION, ALLOCATABLE :: ARRAY(:)
      STATUS=0
      CALL GETARG(1,FILENAME)
      WRITE(*,*) 'INPUT: ',FILENAME
      CALL GETARG(2,ARG)
      READ(ARG,*) FPIXELS(1)
      CALL GETARG(3,ARG)
      READ(ARG,*) FPIXELS(2)
      CALL GETARG(4,ARG)
      READ(ARG,*) FPIXELS(3)
      CALL GETARG(5,ARG)
      READ(ARG,*) LPIXELS(1)
      CALL GETARG(6,ARG)
      READ(ARG,*) LPIXELS(2)
      CALL GETARG(7,ARG)
      READ(ARG,*) LPIXELS(3)
      NAXES(1)=LPIXELS(1)-FPIXELS(1)+1
      NAXES(2)=LPIXELS(2)-FPIXELS(2)+1
      NAXES(3)=LPIXELS(3)-FPIXELS(3)+1
      NPIXELS=NAXES(1)*NAXES(2)
      ALLOCATE(ARRAY(NPIXELS))

C  Start the Simple shift-and-add routine.
      CALL SSAREC(FILENAME,FPIXELS,LPIXELS,ARRAY)

      CALL GETARG(8,FILENAME)
      WRITE(*,*) 'OUTPUT: ',FILENAME
      FPIXELS(1)=1
      FPIXELS(2)=1
      FPIXELS(3)=1
      LPIXELS(1)=NAXES(1)
      LPIXELS(2)=NAXES(2)
      LPIXELS(3)=1
      CALL WRITEIMAGE(FILENAME,FPIXELS,LPIXELS,ARRAY)
      DEALLOCATE(ARRAY)
      STOP
      END
C **********************************************************************
      SUBROUTINE SSAREC(FILENAME,FPIXELS,LPIXELS,ARRAY)
      INTEGER :: FPIXELS(*),LPIXELS(*),K,NPIXELS,F(3),L(3)
      CHARACTER*(*) :: FILENAME
      DOUBLE PRECISION :: ARRAY(*),DA
      DOUBLE PRECISION, ALLOCATABLE :: BUFFER(:)
      INTEGER :: NAXES(3)
      NAXES(1)=LPIXELS(1)-FPIXELS(1)+1
      NAXES(2)=LPIXELS(2)-FPIXELS(2)+1
      NAXES(3)=LPIXELS(3)-FPIXELS(3)+1
      NPIXELS=NAXES(1)*NAXES(2)
      F(1)=FPIXELS(1)
      F(2)=FPIXELS(2)
      L(1)=LPIXELS(1)
      L(2)=LPIXELS(2)
      ALLOCATE(BUFFER(NPIXELS))
      DO K=1,NPIXELS
        ARRAY(K)=0
      ENDDO
      DA=1.0
      DO K=FPIXELS(3),LPIXELS(3)
        F(3)=K
        L(3)=K
        CALL READIMAGE(FILENAME,F,L,BUFFER)
        CALL DAXPY(NPIXELS,DA,BUFFER,1,ARRAY,1)
      ENDDO
      DA=1.0/DBLE(NAXES(3))
      CALL DSCAL(NPIXELS,DA,ARRAY,1)
      DEALLOCATE(BUFFER)
      RETURN
      ENDSUBROUTINE SSAREC