      SUBROUTINE SSAREC(INFILE,FPIXELS,LPIXELS,IMG,BG,WORK)
      INTEGER :: FPIXELS(*),LPIXELS(*),NAXES(2)
      INTEGER :: K,NPIXELS,NFRAMES,X,Y,XC,YC
      DOUBLE PRECISION :: IMG(*),BG(*),DA,DSUM
      DOUBLE PRECISION :: WORK(LPIXELS(1)-FPIXELS(1)+1,*)
      CHARACTER*(*) :: INFILE
      NAXES=(/LPIXELS(1)-FPIXELS(1)+1,LPIXELS(2)-FPIXELS(2)+1/)
      NFRAMES=LPIXELS(3)-FPIXELS(3)+1
      NPIXELS=NAXES(1)*NAXES(2)
      XC=INT(CEILING(0.5*DBLE(NAXES(2)+1)))
      YC=INT(CEILING(0.5*DBLE(NAXES(1)+1)))
      CALL DSCAL(NPIXELS,DBLE(0),IMG,1)
      DO K=FPIXELS(3),LPIXELS(3)
          CALL READIMAGE(INFILE,(/FPIXELS(1),FPIXELS(2),K/),
     &    (/LPIXELS(1),LPIXELS(2),K/),WORK)
        DSUM=SUM(WORK(1:NAXES(1),1:NAXES(2)))
        CALL DSCAL(NPIXELS,DBLE(NPIXELS)/DSUM,WORK,1)
        CALL DAXPY(NPIXELS,DBLE(-1),BG,1,WORK,1)
        X=MAXLOC(MAXVAL(WORK(1:NAXES(1),1:NAXES(2)),1),2)
        Y=MAXLOC(MAXVAL(WORK(1:NAXES(1),1:NAXES(2)),2),1)
        DSUM=SUM(WORK(1:NAXES(1),1:NAXES(2)))
        CALL DSCAL(NPIXELS,DBLE(NPIXELS)/DSUM,WORK,1)
        WORK(1:NAXES(1),1:NAXES(2))=EOSHIFT(
     &    WORK(1:NAXES(1),1:NAXES(2)),X-XC,DBLE(0),2)
        WORK(1:NAXES(1),1:NAXES(2))=EOSHIFT(
     &    WORK(1:NAXES(1),1:NAXES(2)),Y-YC,DBLE(0),1)
        CALL DAXPY(NPIXELS,DBLE(1),WORK,1,IMG,1)
      END DO
      CALL DSCAL(NPIXELS,DBLE(1)/DBLE(NFRAMES),IMG,1)
      RETURN
      END SUBROUTINE SSAREC

