      PROGRAM MAIN
      IMPLICIT NONE
      INTEGER :: FPIXELS(3),LPIXELS(3)
      CHARACTER(LEN=256) :: IMGFILE,SUBFILE,ARG
      INTERFACE
      SUBROUTINE SUBIMAGE(IMGFILE,FPIXELS,LPIXELS,SUBFILE,BUFFERSIZE)
      INTEGER, INTENT(IN) :: FPIXELS(3),LPIXELS(3)
      CHARACTER*(*) :: IMGFILE,SUBFILE
      INTEGER, INTENT(INOUT), OPTIONAL :: BUFFERSIZE
      END SUBROUTINE SUBIMAGE
      END INTERFACE
      CALL GETARG(1,IMGFILE)
      CALL GETARG(2,ARG)
      READ(ARG,*) FPIXELS(1),FPIXELS(2),FPIXELS(3)
      CALL GETARG(3,ARG)
      READ(ARG,*) LPIXELS(1),LPIXELS(2),LPIXELS(3)
      CALL GETARG(4,SUBFILE)
      CALL SUBIMAGE(IMGFILE,FPIXELS,LPIXELS,SUBFILE)
      STOP
      END PROGRAM MAIN
