      PROGRAM MAIN
      IMPLICIT NONE
      INTEGER :: FPIXELS(3),LPIXELS(3)
      CHARACTER(LEN=256) :: IMGFILE,SUBFILE,ARG
      CALL GETARG(1,IMGFILE)
      CALL GETARG(2,ARG)
      READ(ARG,*) FPIXELS(1),FPIXELS(2),FPIXELS(3)
      CALL GETARG(3,ARG)
      READ(ARG,*) LPIXELS(1),LPIXELS(2),LPIXELS(3)
      CALL GETARG(4,SUBFILE)
      CALL SUBIMAGE(IMGFILE,FPIXELS,LPIXELS,SUBIMAGE)
      STOP
      END PROGRAM MAIN
