      PROGRAM BUILDSMTEST
      IMPLICIT NONE
      INTEGER :: N,W,I,J,K,NFRAMES,STATUS
      REAL :: R
      DOUBLE PRECISION, ALLOCATABLE :: DI(:,:)
      CHARACTER(LEN=256) :: ARG
      CALL GETARG(1,ARG)
      READ(ARG,*) N
      CALL GETARG(2,ARG)
      READ(ARG,*) W
      CALL GETARG(3,ARG)
      READ(ARG,*) NFRAMES
      ALLOCATE(DI(N,N))
      STATUS=0
      CALL DELETEFILE('SMTEST.FITS',STATUS)
      DO K=1,NFRAMES
        DI=DBLE(0)
        CALL RANDOM_NUMBER(R)
        I=INT(N/2+(R-0.5)*W)
        CALL RANDOM_NUMBER(R)
        J=INT(N/2+(R-0.5)*W)
        DI(I,J)=1
        CALL APPENDIMAGE('SMTEST.FITS',(/1,1,K/),(/N,N,K/),DI)
      END DO
      DEALLOCATE(DI)
      STOP
      END PROGRAM BUILDSMTEST