      PROGRAM FFC
C  Usage:
C  ======
C  ffc filename_target -flat=filename_flat -dark=filename_dark
C    [-fpixels=n,n,n] [-lpixels=n,n,n] [-o=filename_corrected]
C
C  Purpose:
C  ========
C  Flat field correction
C
      IMPLICIT NONE
      INTEGER :: FPIXELS(3),LPIXELS(3),NARGS,K,NAXES(3)
      CHARACTER(LEN=256) :: ARG,TARGFILE,FLATFILE,DARKFILE,CRCTFILE,
     &  BASENAME,EXTNAME
      INTERFACE
      SUBROUTINE IMAGESIZE(IMGFILE,NAXES)
      CHARACTER*(*), INTENT(IN) :: IMGFILE
      INTEGER, INTENT(OUT) :: NAXES(3)
      END SUBROUTINE IMAGESIZE
      SUBROUTINE PRINTERROR(STATUS)
      INTEGER, INTENT(IN) :: STATUS
      END SUBROUTINE PRINTERROR
      SUBROUTINE DELETEFILE(FILENAME,STATUS)
      INTEGER, INTENT(INOUT) :: STATUS
      CHARACTER*(*), INTENT(IN) :: FILENAME
      END SUBROUTINE DELETEFILE
      SUBROUTINE RESOLVEPATH(PATH,BASENAME,EXTNAME)
      CHARACTER*(*), INTENT(IN) :: PATH
      CHARACTER*(*), INTENT(OUT) :: BASENAME,EXTNAME
      END SUBROUTINE RESOLVEPATH
      SUBROUTINE FLATFIELDCORRECT(TARGFILE,FLATFILE,DARKFILE,
     &  FPIXELS,LPIXELS,CRCTFILE)
      INTEGER, INTENT(IN) :: FPIXELS(3),LPIXELS(3)
      CHARACTER*(*), INTENT(IN) :: TARGFILE,FLATFILE,DARKFILE,CRCTFILE
      END SUBROUTINE FLATFIELDCORRECT
      END INTERFACE
      NARGS=COMMAND_ARGUMENT_COUNT()
      CALL GET_COMMAND_ARGUMENT(1,TARGFILE)
      CALL RESOLVEPATH(TARGFILE,BASENAME,EXTNAME)
      CRCTFILE=TRIM(BASENAME)//'_crct.fits'
      CALL IMAGESIZE(TARGFILE,NAXES)
      FPIXELS=(/1,1,1/)
      LPIXELS=NAXES
      DO K=2,NARGS
        CALL GET_COMMAND_ARGUMENT(K,ARG)
        IF(INDEX(ARG,'-flat=').GT.0)THEN
          READ(ARG(INDEX(ARG,'-flat=')+6:256),*) FLATFILE
        ELSE IF(INDEX(ARG,'-dark=').GT.0)THEN
          READ(ARG(INDEX(ARG,'-dark=')+6:256),*) DARKFILE
        ELSE IF(INDEX(ARG,'-fpixels=').GT.0)THEN
          READ(ARG(INDEX(ARG,'-fpixels=')+9:256),*)
     &      FPIXELS(1),FPIXELS(2),FPIXELS(3)
        ELSE IF(INDEX(ARG,'-lpixels=').GT.0)THEN
          READ(ARG(INDEX(ARG,'-lpixels=')+9:256),*)
     &      LPIXELS(1),LPIXELS(2),LPIXELS(3)
        ELSE IF(INDEX(ARG,'-o=').GT.0)THEN
          READ(ARG(INDEX(ARG,'-o=')+3:256),*) CRCTFILE
        ELSE
          PRINT *,'Unknown argument '//TRIM(ARG)
          RETURN
        END IF
      END DO
      CALL FLATFIELDCORRECT(TARGFILE,FLATFILE,DARKFILE,
     &  FPIXELS,LPIXELS,CRCTFILE)
      STOP
      END PROGRAM FFC
