      PROGRAM FITSINFO
      IMPLICIT NONE
      INTEGER :: STATUS,NAXES(3),NARGS,K,N
      DOUBLE PRECISION,ALLOCATABLE :: DFITS(:,:)
      CHARACTER(LEN=256) :: FILENAME,ARG
      INTERFACE
      SUBROUTINE READIMAGE(FILENAME,FPIXELS,LPIXELS,DIMG)
      INTEGER, INTENT(IN) :: FPIXELS(3),LPIXELS(3)
      DOUBLE PRECISION, INTENT(OUT) :: DIMG(*)
      CHARACTER(LEN=*), INTENT(IN) :: FILENAME
      END SUBROUTINE READIMAGE
      SUBROUTINE IMAGESIZE(FILENAME,NAXES)
      INTEGER, INTENT(IN) :: NAXES(3)
      CHARACTER(LEN=*), INTENT(IN) :: FILENAME
      END SUBROUTINE IMAGESIZE
      END INTERFACE
      STATUS=0
      NARGS=COMMAND_ARGUMENT_COUNT()
      CALL GET_COMMAND_ARGUMENT(1,ARG);
      IF(INDEX(ARG,'-help').GT.0)THEN
        PRINT *,'Usage:'
        PRINT *,'======'
        PRINT *,'fitsinfo filename [-frame=n]'
        STOP
      END IF
      CALL GET_COMMAND_ARGUMENT(1,FILENAME)
      CALL IMAGESIZE(FILENAME,NAXES)
      WRITE(*,'(A,I4)')' x axis length: ',NAXES(1)
      WRITE(*,'(A,I4)')' y axis length: ',NAXES(2)
      WRITE(*,'(A,I5)')' z axis length: ',NAXES(3)
      N=1
      DO K=2,NARGS
        CALL GET_COMMAND_ARGUMENT(K,ARG)
        IF(INDEX(ARG,'-frame=').GT.0)THEN
          READ(ARG(INDEX(ARG,'-frame=')+7:),*) N
        END IF
      END DO
      ALLOCATE(DFITS(NAXES(1),NAXES(2)),STAT=STATUS)
      IF(STATUS.NE.0)THEN
        PRINT *,'out of memory.'
        RETURN
      END IF
      CALL READIMAGE(FILENAME,(/1,1,N/),(/NAXES(1),NAXES(2),N/),DFITS)
      WRITE(*,'(A,ES15.8)')' min: ',MINVAL(DFITS)
      WRITE(*,'(A,ES15.8)')' max: ',MAXVAL(DFITS)
      DEALLOCATE(DFITS)
      STOP
      END PROGRAM FITSINFO
