      PROGRAM IFFTSHIFT
      IMPLICIT NONE
C
      INTEGER :: STATUS,NAXES(3),NARGS
      DOUBLE PRECISION, ALLOCATABLE :: DIMG(:,:)
      CHARACTER(LEN=256) :: INFILE,OUTFILE
C
      INTERFACE
      SUBROUTINE DFFTSHIFT(NX,NY,DX)
      INTEGER, INTENT(IN) :: NX,NY
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NX,NY)
      END SUBROUTINE DFFTSHIFT
      SUBROUTINE DIFFTSHIFT(NX,NY,DX)
      INTEGER, INTENT(IN) :: NX,NY
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NX,NY)
      END SUBROUTINE DIFFTSHIFT
      SUBROUTINE IMAGESIZE(FILENAME,NAXES)
      INTEGER, INTENT(OUT) :: NAXES(3)
      CHARACTER(LEN=*) :: FILENAME
      END SUBROUTINE IMAGESIZE
      SUBROUTINE WRITEIMAGE(FILENAME,FPIXELS,LPIXELS,DIMG)
      INTEGER, INTENT(IN) :: FPIXELS(3),LPIXELS(3)
      DOUBLE PRECISION, INTENT(IN) :: DIMG(*)
      CHARACTER(LEN=*), INTENT(IN) :: FILENAME
      END SUBROUTINE WRITEIMAGE
      SUBROUTINE READIMAGE(FILENAME,FPIXELS,LPIXELS,DIMG)
      INTEGER, INTENT(IN) :: FPIXELS(3),LPIXELS(3)
      DOUBLE PRECISION, INTENT(OUT) :: DIMG(*)
      CHARACTER(LEN=*), INTENT(IN) :: FILENAME
      END SUBROUTINE READIMAGE
      END INTERFACE
C
      STATUS=0
      NARGS=COMMAND_ARGUMENT_COUNT()
      IF(NARGS .LT. 1)THEN
        PRINT *,'Usage:'
        PRINT *,'======'
        PRINT *,'ifftshift image [image]'
        STOP
      END IF
      CALL GET_COMMAND_ARGUMENT(1,INFILE)
      CALL GET_COMMAND_ARGUMENT(NARGS,OUTFILE)
      PRINT *,'input: '//TRIM(INFILE)
      PRINT *,'output: '//TRIM(OUTFILE)
      CALL IMAGESIZE(INFILE,NAXES)
      ALLOCATE(DIMG(NAXES(1),NAXES(2)),STAT=STATUS)
      IF(STATUS .NE. 0)THEN
        WRITE(*,*)'error: out of memory.'
        STOP
      END IF
      CALL READIMAGE(INFILE,(/1,1,1/),(/NAXES(1),NAXES(2),1/),DIMG)
      CALL DIFFTSHIFT(NAXES(1),NAXES(2),DIMG)
      CALL WRITEIMAGE(OUTFILE,(/1,1,1/),(/NAXES(1),NAXES(2),1/),DIMG)
      DEALLOCATE(DIMG)
      STOP
      END PROGRAM IFFTSHIFT
