      PROGRAM IMG2SPE
      IMPLICIT NONE
      INTEGER :: STATUS,NAXES(3),NARGS
      DOUBLE PRECISION, ALLOCATABLE :: DRHO(:,:),DPHI(:,:),DIMG(:,:)
      DOUBLE COMPLEX, ALLOCATABLE :: ZSPE(:,:)
      CHARACTER(LEN=256) :: MODFILE,PHAFILE,IMGFILE
C
      INTERFACE
      SUBROUTINE DFFTSHIFT(NX,NY,DX)
      INTEGER, INTENT(IN) :: NX,NY
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NX,NY)
      END SUBROUTINE DFFTSHIFT
      SUBROUTINE DIFFTSHIFT(NX,NY,DX)
      INTEGER, INTENT(IN) :: NX,NY
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NX,NY)
      END SUBROUTINE DIFFTSHIFT
      SUBROUTINE IMAGESIZE(FILENAME,NAXES)
      INTEGER, INTENT(OUT) :: NAXES(3)
      CHARACTER(LEN=*) :: FILENAME
      END SUBROUTINE IMAGESIZE
      SUBROUTINE WRITEIMAGE(FILENAME,FPIXELS,LPIXELS,DIMG)
      INTEGER, INTENT(IN) :: FPIXELS(3),LPIXELS(3)
      DOUBLE PRECISION, INTENT(IN) :: DIMG(*)
      CHARACTER(LEN=*), INTENT(IN) :: FILENAME
      END SUBROUTINE WRITEIMAGE
      SUBROUTINE IMAGETOSPECTRUM(NX,NY,DIMG,ZSPE)
      INTEGER, INTENT(IN) :: NX,NY
      DOUBLE PRECISION, INTENT(IN) :: DIMG(NX,NY)
      DOUBLE COMPLEX, INTENT(OUT) :: ZSPE(NX,NY)
      END SUBROUTINE IMAGETOSPECTRUM
      SUBROUTINE READIMAGE(FILENAME,FPIXELS,LPIXELS,DIMG)
      INTEGER, INTENT(IN) :: FPIXELS(3),LPIXELS(3)
      DOUBLE PRECISION, INTENT(OUT) :: DIMG(*)
      CHARACTER(LEN=*), INTENT(IN) :: FILENAME
      END SUBROUTINE READIMAGE
      END INTERFACE
C
      STATUS=0
      NARGS=COMMAND_ARGUMENT_COUNT()
      IF(NARGS .LT. 3)THEN
        PRINT *,'Usage:'
        PRINT *,'======'
        PRINT *,'img2spe image modulus phase'
        STOP
      END IF
      CALL GET_COMMAND_ARGUMENT(1,IMGFILE)
      CALL GET_COMMAND_ARGUMENT(2,MODFILE)
      CALL GET_COMMAND_ARGUMENT(3,PHAFILE)
      PRINT *,'input image: '//TRIM(IMGFILE)
      PRINT *,'output modulus: '//TRIM(MODFILE)
      PRINT *,'output phase: '//TRIM(PHAFILE)
C
      ALLOCATE(DRHO(NAXES(1),NAXES(2)),STAT=STATUS)
      IF(STATUS .NE. 0)THEN
        WRITE(*,*)'error: out of memory.'
        STOP
      END IF
      ALLOCATE(DPHI(NAXES(1),NAXES(2)),STAT=STATUS)
      IF(STATUS .NE. 0)THEN
        WRITE(*,*)'error: out of memory.'
        STOP
      END IF
      ALLOCATE(ZSPE(NAXES(1),NAXES(2)),STAT=STATUS)
      IF(STATUS .NE. 0)THEN
        WRITE(*,*)'error: out of memory.'
        STOP
      END IF
      ALLOCATE(DIMG(NAXES(1),NAXES(2)),STAT=STATUS)
      IF(STATUS .NE. 0)THEN
        WRITE(*,*)'error: out of memory.'
        STOP
      END IF
C
      CALL READIMAGE(IMGFILE,(/1,1,1/),(/NAXES(1),NAXES(2),1/),DIMG)
      CALL IMAGETOSPECTRUM(NAXES(1),NAXES(2),DIMG,ZSPE)
      DRHO=ZABS(ZSPE)
      DPHI=DATAN2(DIMAG(ZSPE),DREAL(ZSPE))
      CALL WRITEIMAGE(MODFILE,(/1,1,1/),(/NAXES(1),NAXES(2),1/),DRHO)
      CALL WRITEIMAGE(PHAFILE,(/1,1,1/),(/NAXES(1),NAXES(2),1/),DPHI)
      DEALLOCATE(DRHO)
      DEALLOCATE(DPHI)
      DEALLOCATE(DIMG)
      DEALLOCATE(ZSPE)
      STOP
      END PROGRAM IMG2SPE
