      PROGRAM POISSRNDTEST
      IMPLICIT NONE
      INTEGER, PARAMETER :: KMAX = 10000, L=4
      INTEGER :: K
      DOUBLE PRECISION :: DMU(L,1),DSIGMA(L,1)
      INTERFACE
      SUBROUTINE INIT_RANDOM_SEED()
      END SUBROUTINE INIT_RANDOM_SEED
      FUNCTION NORMRND(NX,NY,DMU,DSIGMA)
      INTEGER, INTENT(IN) :: NX,NY
      DOUBLE PRECISION, INTENT(IN) :: DMU(NX,NY),DSIGMA(NX,NY)
      DOUBLE PRECISION :: NORMRND(NX,NY)
      END FUNCTION NORMRND
      END INTERFACE
      READ(*,*)DMU(:,1)
      READ(*,*)DSIGMA(:,1)
      CALL INIT_RANDOM_SEED()
      DO K=1,KMAX
        WRITE(*,*) NORMRND(L,1,DMU,DSIGMA)
      END DO
      STOP
      END PROGRAM POISSRNDTEST

