      SUBROUTINE SIREC(OBSFILE,FPOBS,LPOBS,DROBS,
     &  REFFILE,FPREF,LPREF,DRREF,P,FTMETHOD,DACF)
C  Declarations:
C  =============
      INCLUDE 'fftw3.f'
      INTEGER*8 :: PLAN
      INTEGER, INTENT(IN):: FPOBS(3),LPOBS(3),FPREF(3),LPREF(3),P,
     &  FTMETHOD
      DOUBLE PRECISION, INTENT(OUT) :: DACF(P,P)
      DOUBLE PRECISION :: DPSDOBS(P,P),DPSDREF(P,P)
      DOUBLE PRECISION, INTENT(IN) :: DROBS,DRREF
      DOUBLE COMPLEX :: ZIN(P,P),ZOUT(P,P)
      CHARACTER*(*), INTENT(IN) :: OBSFILE,REFFILE
C  Statements:
C  ===========
      CALL GETPSD(OBSFILE,FPOBS,LPOBS,DROBS,P,FTMETHOD,DPSDOBS)
      CALL GETPSD(REFFILE,FPREF,LPREF,DRREF,P,FTMETHOD,DPSDREF)
      DACF=DPSDOBS/DPSDREF
      CALL DFFTW_PLAN_DFT_2D(PLAN,P,P,ZIN,ZOUT,1,
     &  FFTW_ESTIMATE+FFTW_DESTROY_INPUT)
      ZIN=CMPLX(DACF)
      CALL DFFTW_EXECUTE_DFT(PLAN,ZIN,ZOUT)
      DACF=DBLE(ZOUT)
      CALL DFFTSHIFT(P,P,DACF)
      CALL DFFTW_DESTROY_PLAN(PLAN)
      RETURN
      END SUBROUTINE SIREC
C
