      PROGRAM MAIN
      IMPLICIT NONE
      INTEGER :: FPIXELS(3),LPIXELS(3),P,MW,BUFFERSIZE,M,N,NBISP
      DOUBLE PRECISION :: DR
      DOUBLE PRECISION, ALLOCATABLE :: DAVG(:,:)
      DOUBLE COMPLEX, ALLOCATABLE :: ZBISP(:)
      CHARACTER(LEN=256) :: FILENAME,ARG,AVGFILE
      CHARACTER(LEN=10) :: FTMETHOD
      CALL GETARG(1,FILENAME)
      CALL GETARG(2,ARG)
      READ(ARG,*) FPIXELS(1),FPIXELS(2),FPIXELS(3)
      CALL GETARG(3,ARG)
      READ(ARG,*) LPIXELS(1),LPIXELS(2),LPIXELS(3)
      CALL GETARG(4,AVGFILE)
      CALL GETARG(5,ARG)
      READ(ARG,*) DR
      CALL GETARG(6,FTMETHOD)
      CALL GETARG(7,ARG)
      READ(ARG,*) P
C  The padding size must be even:
      P=INT(CEILING(DBLE(P)/DBLE(2))*DBLE(2))
      CALL GETARG(8,ARG)
      READ(ARG,*) MW
      CALL GETARG(9,ARG)
      READ(ARG,*) BUFFERSIZE
      M=LPIXELS(1)-FPIXELS(1)+1
      N=LPIXELS(2)-FPIXELS(2)+1
      ALLOCATE(DAVG(M,N))
      CALL READIMAGE(AVGFILE,(/1,1,1/),(/M,N,1/),DAVG)
      NBISP=MW*(2*P-MW-1)*P*P/8
      ALLOCATE(ZBISP(NBISP))
      CALL BISPECTRUM(FILENAME,FPIXELS,LPIXELS,DAVG,DR,FTMETHOD,
     &  P,MW,BUFFERSIZE,ZBISP)
      DEALLOCATE(ZBISP)
      STOP
      END PROGRAM MAIN