      PROGRAM MAIN
      IMPLICIT NONE
      INTEGER :: FPIXELS(3),LPIXELS(3)
      CHARACTER(LEN=256) :: IMGFILE,SUBFILE,ARG
      INTERFACE
      INCLUDE 'ispeckle.f'
      END INTERFACE
      CALL GET_COMMAND_ARGUMENT(1,IMGFILE)
      CALL GET_COMMAND_ARGUMENT(2,ARG)
      READ(ARG,*) FPIXELS(1),FPIXELS(2),FPIXELS(3)
      CALL GET_COMMAND_ARGUMENT(3,ARG)
      READ(ARG,*) LPIXELS(1),LPIXELS(2),LPIXELS(3)
      CALL GET_COMMAND_ARGUMENT(4,SUBFILE)
      CALL SUBIMAGE(IMGFILE,FPIXELS,LPIXELS,SUBFILE)
      STOP
      END PROGRAM MAIN
